name: Node CI/CD
on: push
jobs:
  build-node:
    name: Build and run node ci/cd
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
        name: node version
      - run: npm --version
        name: npm version
      - uses: actions/checkout@v3
        name: checkout code from github
      - run: npm install
        name: install dependencies
      - run: npm run test
        name: unit Test
      - run: npm run build
        name: build app
      - uses: actions/upload-artifact@v3
        name: upload artifacts dist build
        with:
          name: dist-build
          path: dist/
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-node
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-build
      - name: Test artificact download
        run: ls -R
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: app.zip
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
